host = "https://csc466-router.baxtergroup.io"

# time to wait for a single page request
# (may incorporate multiple subrequests for dependent objects)
page-load-timeout = 60

# number of times to repeat each test (sample size)
iterations = 50

# Currently this is run manually and separately, so these options are not in use:

# Chrome location
chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

quic-debugging-port = 9221
quic-user-data-dir = '/tmp/quic-user-data-dir'
tcp-debugging-port = 9220
tcp-user-data-dir = '/tmp/tcp-user-data-dir'
chrome-startup-delay = 2

# Chrome options
chrome-options = [
	"--disable-gpu",
	"--no-first-run",
	"--disable-background-networking",
	"--disable-client-side-phishing-detection",
	"--disable-component-update",
	"--disable-default-apps",
	"--disable-hang-monitor",
	"--disable-popup-blocking",
	"--disable-prompt-on-repost",
	"--disable-sync",
	"--disable-web-resources",
	"--metrics-recording-only",
	"--password-store=basic",
	"--safebrowsing-disable-auto-update",
	"--use-mock-keychain",
	"--enable-benchmarking",
	"--enable-net-benchmarking"
]

[treatment]

	delay-time = 0 # ms
	delay-jitter = 0 # ms
	delay-correlation = 25 # %
	# one of: uniform, normal, pareto, paretonormal
	delay-distribution = 'normal'

	# Gilbert-Elliot model
	loss-p = 0.0 # [0,1] probability of transition to 'bad state'
	loss-r = 100.0 # [0,1] probability of transition to 'good state'
	loss-h = 100.0 # [0,1] 1 - h is loss probability in the bad state
	loss-k = 0.0 # [0,1] 1 - k is loss probability in the good state

	# introducing bit errors in packets
	corrupt-percent = 0.0 # %
	corrupt-correlation = 25 # %

	duplicate-percent = 0.0 # %
	duplicate-correlation = 25 # %

	# tc qdisc ceil in mbit
	rate-limit = 50.0

	# images on page
	object-count = 5

	# size of images on page
	object-size = 10

[variations]

	rate-limit = [1.0, 5.0, 10.0, 25.0, 50.0]
	object-count = [5, 10, 50, 100, 200]
	object-size = [5, 10, 100, 200, 500, 1000]
	loss-p = [0.0, 1.0, 2.0, 3.0, 5.0]
	corrupt-percent = [0.0, 1.0, 2.0, 3.0, 5.0]
	duplicate-percent = [0.0, 1.0, 2.0, 3.0, 5.0]
	delay-time = [0, 50, 100, 150, 200]
	delay-jitter = [0, 20, 40, 60, 80, 100]

[[dual-variations]]

	axis1 = 'delay-time'
	axis2 = 'delay-jitter'
	values = []
