host = "https://csc466-router.baxtergroup.io"

# tc qdisc ceil in mbit
rate-limit = 10.0
rate-limits = [] # 0.1, 1.0, 10.0]

# tc qdisc latency in ms
latency = 0
latencies = [0, 50] #, 100, 1000]

# tc qdisc netem loss in %
packet-loss = 0.0
packet-losses = [] #, 1.0, 10.0]

# images on page
object-count = 0
object-counts = [] #, 1, 2]

# size of images on page
object-size = 100
object-sizes = []

available-image-sizes = [5, 10, 100, 200, 500, 1000, 10000]

# time to wait for a single page request
# (may incorporate multiple subrequests for dependent objects)
page-load-timeout = 60

# number of times to repeat each test (sample size)
iterations = 100

# Currently this is run manually and separately, so these options are not in use:

# Chrome location
chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

quic-debugging-port = 9221
quic-user-data-dir = '/tmp/quic-user-data-dir'
tcp-debugging-port = 9220
tcp-user-data-dir = '/tmp/tcp-user-data-dir'
chrome-startup-delay = 2

# Chrome options
chrome-options = [
	"--disable-gpu",
	"--no-first-run",
	"--disable-background-networking",
	"--disable-client-side-phishing-detection",
	"--disable-component-update",
	"--disable-default-apps",
	"--disable-hang-monitor",
	"--disable-popup-blocking",
	"--disable-prompt-on-repost",
	"--disable-sync",
	"--disable-web-resources",
	"--metrics-recording-only",
	"--password-store=basic",
	"--safebrowsing-disable-auto-update",
	"--use-mock-keychain",
	"--enable-benchmarking",
	"--enable-net-benchmarking",
	"--headless"
]


