host = "www.example.org"

# Mbps
rate-limits = [1, 5, 10]

# ms
extra-delay = [0, 50, 100]

# %
extra-loss = [0.1, 1.0]

# on page
number-objects = [1, 2, 5, 10,0, 200]

# KB
object-sizes = [5, 10, 100]

# seconds
page-load-timeout = 120

# Chrome options
chrome-options = [
	"--no-first-run",
	"--disable-background-networking",
	"--disable-client-side-phishing-detection",
	"--disable-component-update",
	"--disable-default-apps",
	"--disable-hang-monitor",
	"--disable-popup-blocking",
	"--disable-prompt-on-repost",
	"--disable-sync",
	"--disable-web-resources",
	"--metrics-recording-only",
	"--password-store=basic",
	"--safebrowsing-disable-auto-update",
	"--use-mock-keychain",
	"--ignore-certificate-errors",
	"--enable-benchmarking",
	"--enable-net-benchmarking"
]


