host = "https://csc466-router.baxtergroup.io"

# tc qdisc ceil in mbit
rate-limit = 1000.0
rate-limits = [0.1, 1.0, 5.0, 10.0]

# tc qdisc latency in ms
latency = 0
latencies = [0, 50, 100, 500, 1000]

# tc qdisc netem loss in %
packet-loss = 0.0
packet-losses = [0.0, 0.1, 1.0, 3.0]

# images on page
object-count = 2
object-counts = [0, 1, 2, 5, 100, 200]

# size of images on page
object-size = 100
object-sizes = [5, 10, 100]

# time to wait for a single page request
# (may incorporate multiple subrequests for dependent objects)
page-load-timeout = 60

webroot = 'root'



# Currently this is run manually and separately, so these options are not in use:

# Chrome location
chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

# Chrome options
chrome-options = [
	"--disable-gpu",
	"--remote-debugging-port=9922",
	"--no-first-run",
	"--disable-background-networking",
	"--disable-client-side-phishing-detection",
	"--disable-component-update",
	"--disable-default-apps",
	"--disable-hang-monitor",
	"--disable-popup-blocking",
	"--disable-prompt-on-repost",
	"--disable-sync",
	"--disable-web-resources",
	"--metrics-recording-only",
	"--password-store=basic",
	"--safebrowsing-disable-auto-update",
	"--use-mock-keychain",
	"--ignore-certificate-errors",
	"--enable-benchmarking",
	"--enable-net-benchmarking",
	"--headless"
]


